### ISSUE TITLE
クロスプラットフォームに対応できますか？

### ISSUE THREAD

**Issue by keito940** [TeamElement/DxLib#2]
どうも、keito940です。公式で配布されているC#のDXライブラリを見たのですが、どうも、C言語色が強くて不便ですね。ですが、このライブラリーはC#を前提とした改造が施されているので、C#慣れした人でもかんたんに作れそうだと思いますが、DirectXを使うという都合上、Windowsしか使えないのが難点です。そこで、SDLを使うDxPortLibのようにクロスプラットフォームに対応して、楽に移植できるようにしてほしいことと、C#使いにとってはマイナーなのはいただけないので、このライブラリをC#使いに更に広めてみればいかがかと…。
また、このライブラリーをJavaにも作っておけば、本格的なゲームづくりのためにLWGJLとかを使っていたJava使いでも、楽に本格的なゲームができるのではないのでしょうか？
あと、このライブラリのサンプルプログラムを付け加えてください。

**Comment by DSTLC-VSIN** [comment]
分かりました。チーム内で検討してみます。

**Comment by DSTLC-VSIN** [comment]
検討させていただいた結果、他の派生ライブラリにも対応しやすいように、設計を見直すことにしました。
少々作業が増えるので、時間はかかると思いますが、気長にお待ちいただけると幸いです。

Java版についてですが、まずは.NET版を完成させて、問題なさそうであれば開発したいと思っています。

**Comment by DSTLC-VSIN** [comment]
本件について、新プロジェクトで対応することにしました。
新プロジェクトはこちらになります。
https://github.com/TeamElement/DxLib.NET
