### ISSUE TITLE
F#やVisual Basicなどと言った.NETを使う言語のサポート

### ISSUE THREAD

**Issue by keito940** [TeamElement/DxLib#4]
SDLによるクロスプラットフォームやJavaへの対応（快く検討すると言ってくれましたね）の件で質問したものです。
.Net WarperということはF#やVisual Basicと言った.NET系言語にも対応しているということですよね？
つまり、UnityやMonoGame(XNA)の癖になれない人でもDXライブラリとほぼ同じ感覚で.NETを使ってゲームが作れるというわけですか？

**Comment by DSTLC-VSIN** [comment]
はい。大体はその通りです。

DXライブラリを使い慣れている方は、関数が複数のクラスに分別されているので、その関数がどのクラスに分別されたかを覚えるだけでOKです。
